version: "3.9"
services:
  backend:
    build: ./backend
    container_name: underover-backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: underover-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - backend
