services:
  - type: web
    name: underover-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: 
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /health
    autoDeploy: true
    region: frankfurt

  - type: web
    name: underover-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://underover-backend.onrender.com
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
    region: frankfurt

